In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [4]:
# no hidden layer weights
weights = 2* np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[-0.58543133],
        [ 0.64228047]]),
 array([-0.18357515]))

In [5]:
# forward propagation without any hidden layer
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[0.45423467],
       [0.612707  ],
       [0.31669406],
       [0.46836083]])

In [6]:
# one hidden layer weights
wh = 2* np.random.random((2, 2)) - 1
bh = 2* np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1,1)) - 1
wh,bh,wo,bo

(array([[-0.18678569, -0.26291664],
        [ 0.50597029, -0.54316524]]),
 array([[-0.18361193, -0.64496646]]),
 array([[ 0.36706176],
        [-0.96399611]]),
 array([[-0.33677014]]))

In [7]:
# forward propagation with one hidden layer
output0 = X
outputHidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputHidden, wo) + bo)
output

array([[0.37712334],
       [0.41360204],
       [0.38605391],
       [0.41974441]])