### Q1. Make Function for Mean, Median, Mode, Mean Square, Standard Deviation, Variance.

In [28]:
x = [0,1,2,3,4,5,6,7,8,9]

def mean(y):
    s=0
    for i in range(len(y)):
        s=s+y[i]
        y_mean=s/len(y)
    return y_mean

print(mean(x))

4.5


In [30]:
x = [0,1,2,3,4,5,6,7,8]

def median(y):
    data = sorted(y)
    index = len(data) // 2
 
    if len(y) % 2!= 0:
        return data[index]

    return (data[index - 1] + data[index]) / 2

print(median(x))

4


In [31]:
x = [0,1,2,3,4,5,6,7,9,9]

def mode(y):
    frequency = {}
    for value in y:
        frequency[value] = frequency.get(value, 0) + 1
    most_frequent = max(frequency.values())
    modes = [key for key, value in frequency.items()if value == most_frequent]
    return modes

print(mode(x))

[9]


In [35]:
x = [0,1,2,3,4,5,6,7,8,9]

def root_mean_sqrt(y):
    sq=[]
    for i in range(len(y)):
        sq.append((y[i]**2))
    mean = sum(sq)/len(sq)
    return mean**(1/2)

print(root_mean_sqrt(x))  

5.338539126015656


In [36]:
x = [0,1,26,3,4,5,16,37,19,29]

def variance(data): 
    n = len(data) 
    mean = sum(data) / n 
    deviations = [(x - mean) ** 2 for x in data] 
    variance = sum(deviations) / n
    return variance

print(variance(x))

159.4


In [37]:
import math

x = [0,1,26,3,4,5,16,37,19,29]

def standard_devition(y):
    var = variance(y)
    std_dev = (var)**0.5
    return std_dev

print(standard_devition(x))

12.625371281669304


### Q2. Apply Linear Regression on data set imported from scikit Learn.

In [82]:
import pandas as pd
import sklearn.datasets as data
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

boston = data.load_boston()

In [50]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [75]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [70]:
x = boston.data
y = boston.target
xtrain, xtest, ytrain, ytest = train_test_split(x,y)
print(xtrain.shape)
print(xtest.shape)
print(ytest.shape)
print(x.shape)
print(y.shape)

(379, 13)
(127, 13)
(127,)
(506, 13)
(506,)


In [55]:
model = LinearRegression()
model.fit(xtrain,ytrain)

LinearRegression()

In [58]:
model.score(xtest,ytest)

0.7151543860342805

### Q3. Input two features and print predicted y numeric value

In [81]:
new_input = [[6.32, 1.8, 2.31, 1, 1, 1, 1, 1, 1, 1, 1.53, 3.969, 4.98]]
output = model.predict(new_input)
print(new_input, output)

[[6.32, 1.8, 2.31, 1, 1, 1, 1, 1, 1, 1, 1.53, 3.969, 4.98]] [17.92617115]


### Q4. Gaussian, Bernoulli, Multinomial on iris dataset by using Naive Bayes

In [272]:
import pandas as pd
import sklearn.datasets as data
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB

iris = data.load_iris()
x = iris.data
y = iris.target
xtrain, xtest, ytrain, ytest = train_test_split(x,y)
y_test = np.reshape(ytest, (-1, 1))

In [273]:
gnb = GaussianNB()
gnb.fit(xtrain, ytrain)

GaussianNB()

In [274]:
y_pred = gnb.predict(xtest)
y_pred

array([1, 2, 1, 1, 2, 2, 1, 0, 1, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 2, 2, 0, 0, 0, 1, 2, 2, 0, 1, 0, 1, 0, 1, 2])

In [275]:
accuracy_score(y_pred, ytest)

0.9736842105263158

In [276]:
bnb = BernoulliNB()
bnb.fit(xtrain, ytrain)

BernoulliNB()

In [277]:
y_pred = bnb.predict(xtest)
y_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [278]:
accuracy_score(y_pred, ytest)

0.2631578947368421

In [279]:
mnb = MultinomialNB()
mnb.fit(xtrain, ytrain)

MultinomialNB()

In [280]:
y_pred = mnb.predict(xtest)
y_pred

array([2, 2, 2, 1, 2, 2, 2, 0, 1, 2, 0, 0, 0, 1, 2, 0, 0, 2, 0, 2, 0, 1,
       1, 2, 2, 0, 0, 0, 2, 2, 2, 0, 2, 0, 1, 0, 1, 2])

In [281]:
accuracy_score(y_pred, ytest)

0.8157894736842105

### Q5. Implement SVM

In [283]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [284]:
iris = data.load_iris()
x = iris.data
y = iris.target
x_train, x_test, y_train, y_test = train_test_split(x,y)
print(x_train.shape)
print(x_test.shape)

(112, 4)
(38, 4)


In [285]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [286]:
from sklearn.svm import SVC

clf = SVC(kernel = 'linear')
clf.fit(x_train,y_train)

SVC(kernel='linear')

In [287]:
y_pred = clf.predict(x_test)
y_pred

array([1, 2, 1, 1, 1, 1, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 0, 0, 2, 0, 0, 2,
       1, 1, 1, 2, 0, 0, 2, 0, 2, 1, 0, 2, 0, 2, 2, 1])

In [288]:
accuracy_score(y_pred, y_test)

0.9210526315789473