In [18]:
import random
a=[[j for j in range(random.randint(1,10))] for i in range(0,10)]
a

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6],
 [0, 1, 2, 3, 4, 5, 6, 7],
 [0, 1, 2, 3],
 [0],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1],
 [0, 1, 2, 3, 4, 5],
 [0, 1, 2, 3, 4, 5],
 [0, 1, 2, 3, 4, 5, 6, 7, 8]]

In [50]:
a = [[1,2,3],[4,5]]
b = [[11,21,31],[41,15,16]]

print(a+b)
print(b*a[0][1])
print(a[1][1])
print(a[0:1])

 

[[1, 2, 3], [4, 5], [11, 21, 31], [41, 15, 16]]
[[11, 21, 31], [41, 15, 16], [11, 21, 31], [41, 15, 16]]
5
[[1, 2, 3]]


In [52]:
n = int(input())
print()

for i in range(1,n+1):
    for j in range(1,i+1):
        print(j, end='')
    for j in range(1,2*n-2*i+1):
        print(" ", end="")
    for j in range(i, 0, -1):
        print(j, end="")
        
    print()    

5

1        1
12      21
123    321
1234  4321
1234554321


In [25]:
import time
import numpy as np
size_of_vec = 100000

def pure_py():
    start_time = time.time()
    x = range(size_of_vec)
    y = range(size_of_vec)
    z = [x[i] + y[i] for i in range(len(x))]
    time_taken = time.time() - start_time
    return time_taken

def numpy():
    T1 = time.time()
    x = np.arange(size_of_vec)
    y = np.arange(size_of_vec)
    z = x+y
    time_taken = time.time() - T1
    return time_taken

t1 = pure_py()
t2 = numpy()
print (t1,t2)
print(t1/t2)
    

0.025005817413330078 0.0019974708557128906
12.518739555979948


In [10]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
arr
print(arr[0,0])
arr>5

1


array([[False, False, False],
       [False, False,  True]])

In [13]:
np.zeros((3,3),int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [24]:
import random
np.random.random((2,2))

array([[0.95761472, 0.22136449],
       [0.98163343, 0.44107278]])

In [26]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.linspace(1, 100, 6)

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [32]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
print(a*3)
print(a+3)
print(a**b)
print(b.mean())
print(a.mean())
print(a.sum())
a.shape

[ 6  8 10 12]
[ 3  6  9 12]
[4 5 6 7]
[    1    64  2187 65536]
6.5
2.5
10


(4,)

In [1]:
import pandas as pd

path = "https://archive.ics.uci.edu/ml/machine-learning-databases/cpu-performance/machine.data"

df = pd.read_csv(path,header=None)
df.head()

0        1    2     3      4    5   6    7    8    9
0  adviser    32/60  125   256   6000  256  16  128  198  199
1   amdahl   470v/7   29  8000  32000   32   8   32  269  253
2   amdahl  470v/7a   29  8000  32000   32   8   32  220  253
3   amdahl  470v/7b   29  8000  32000   32   8   32  172  253
4   amdahl  470v/7c   29  8000  16000   32   8   16  132  132

In [2]:
df.tail()

0              1    2     3     4   5  6   7   8   9
204  sperry           80/8  124  1000  8000   0  1   8  42  37
205  sperry  90/80-model-3   98  1000  8000  32  2   8  46  50
206  sratus             32  125  2000  8000   0  2  14  52  41
207    wang         vs-100  480   512  8000  32  0   0  67  47
208    wang          vs-90  480  1000  4000   0  0   0  45  25

In [5]:
print(df.shape)
print(df.dtypes)

(209, 10)
0    object
1    object
2     int64
3     int64
4     int64
5     int64
6     int64
7     int64
8     int64
9     int64
dtype: object


In [6]:
df.describe()

2             3             4           5           6  \
count   209.000000    209.000000    209.000000  209.000000  209.000000   
mean    203.822967   2867.980861  11796.153110   25.205742    4.698565   
std     260.262926   3878.742758  11726.564377   40.628722    6.816274   
min      17.000000     64.000000     64.000000    0.000000    0.000000   
25%      50.000000    768.000000   4000.000000    0.000000    1.000000   
50%     110.000000   2000.000000   8000.000000    8.000000    2.000000   
75%     225.000000   4000.000000  16000.000000   32.000000    6.000000   
max    1500.000000  32000.000000  64000.000000  256.000000   52.000000   

                7            8            9  
count  209.000000   209.000000   209.000000  
mean    18.267943   105.622010    99.330144  
std     25.997318   160.830733   154.757102  
min      0.000000     6.000000    15.000000  
25%      5.000000    27.000000    28.000000  
50%      8.000000    50.000000    45.000000  
75%     24.000000   113.000000   101.000000  
max    176.000000  1150.000000  1238.000000

In [7]:
df

0              1    2     3      4    5   6    7    8    9
0    adviser          32/60  125   256   6000  256  16  128  198  199
1     amdahl         470v/7   29  8000  32000   32   8   32  269  253
2     amdahl        470v/7a   29  8000  32000   32   8   32  220  253
3     amdahl        470v/7b   29  8000  32000   32   8   32  172  253
4     amdahl        470v/7c   29  8000  16000   32   8   16  132  132
..       ...            ...  ...   ...    ...  ...  ..  ...  ...  ...
204   sperry           80/8  124  1000   8000    0   1    8   42   37
205   sperry  90/80-model-3   98  1000   8000   32   2    8   46   50
206   sratus             32  125  2000   8000    0   2   14   52   41
207     wang         vs-100  480   512   8000   32   0    0   67   47
208     wang          vs-90  480  1000   4000    0   0    0   45   25

[209 rows x 10 columns]